# Generated by Django 5.2.3 on 2025-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('id_type', models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT'), ('CUIL', 'CUIL')], default='DNI', max_length=8, verbose_name='Tipo de Documento')),
                ('id_number', models.CharField(max_length=13)),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
        ),
    ]
