# Generated by Django 5.2.3 on 2025-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
