# Generated by Django 5.2.3 on 2026-06-10 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'flag'], name='clients_cli_user_id_4a63a6_idx'),
        ),
    ]
