# Generated by Django 5.2.3 on 2025-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('mod', 'Modificacion'), ('new', 'Nuevo'), ('delete', 'Eliminacion'), ('file_add', 'Archivo Agregado'), ('file_del', 'Archivo Eliminado')], max_length=30)),
                ('msg', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Estado Parcelario', 'Estado Parcelario'), ('Mensura', 'Mensura'), ('Amojonamiento', 'Amojonamiento'), ('Relevamiento', 'Relevamiento'), ('Legajo Parcelario', 'Legajo Parcelario')], max_length=30, verbose_name='Proyecto')),
                ('type_mens', models.CharField(blank=True, choices=[('PH', 'PH'), ('Usucapion', 'Usucapion'), ('Division', 'Division'), ('Anexion/Division', 'Anexion/Division'), ('Unificacion', 'Unificacion')], max_length=30, null=True, verbose_name='Mensura')),
                ('titular_name', models.CharField(default='', max_length=100, verbose_name='Nombre y apellido')),
                ('titular_phone', models.CharField(max_length=40, verbose_name='Telefono')),
                ('partido', models.CharField(blank=True, max_length=30, verbose_name='Partido')),
                ('partida', models.CharField(blank=True, max_length=30, verbose_name='Partida')),
                ('circ', models.CharField(blank=True, max_length=30, verbose_name='Circunscripcion')),
                ('sect', models.CharField(blank=True, max_length=30, verbose_name='Seccion')),
                ('chacra_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('chacra_let', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('quinta_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('quinta_let', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('fraccion_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('fraccion_let', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('manzana_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('manzana_let', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('parcela_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('parcela_let', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('subparcela', models.CharField(blank=True, max_length=10, verbose_name='Subparcela')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Calle')),
                ('street_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Piso')),
                ('dept', models.CharField(blank=True, max_length=10, verbose_name='Depto')),
                ('inscription_type', models.CharField(choices=[('Folio', 'Folio'), ('Matricula', 'Matricula')], default='', max_length=30, null=True, verbose_name='Inscripcion')),
                ('process_num', models.IntegerField(null=True, verbose_name='N° Tramite')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono de contacto')),
                ('procedure', models.CharField(blank=True, max_length=100, verbose_name='Procedimiento')),
                ('closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
