# Generated by Django 5.2.3 on 2025-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='process_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Tramite'),
        ),
    ]
