# Generated by Django 5.2.3 on 2025-07-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_alter_project_process_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='project_admin.project'),
        ),
    ]
