# Generated by Django 5.2.3 on 2025-07-25 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountmovement_accounting__user_id_afcb86_idx_and_more'),
        ('clients', '0003_client_flag'),
        ('project_admin', '0004_event_project_pk_alter_event_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('modp', 'Modificacion'), ('newp', 'Nuevo'), ('deletep', 'Eliminacion'), ('file_add', 'Archivo Agregado'), ('file_del', 'Archivo Eliminado'), ('newc', 'Cliente Modificado'), ('deletec', 'Cliente Eliminado')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', '-time'], name='project_adm_user_id_cd2755_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'type'], name='project_adm_project_954554_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['partida'], name='project_adm_partida_7d6f43_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'closed'], name='project_adm_user_id_943d62_idx'),
        ),
    ]
