# Generated by Django 5.2.3 on 2025-10-20 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_accountmovement_accounting__user_id_afcb86_idx_and_more"),
        ("clients", "0003_client_flag"),
        ("project_admin", "0005_event_client_pk_alter_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["client", "type"], name="project_adm_client__2fdc8c_idx"
            ),
        ),
    ]
