# Generated by Django 5.2.3 on 2025-12-14 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0006_project_project_adm_client__2fdc8c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='project_admin.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Proyecto',
                'verbose_name_plural': 'Notas de Proyectos',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['project', '-created'], name='project_adm_project_b62c29_idx'), models.Index(fields=['user', '-created'], name='project_adm_user_id_376122_idx')],
            },
        ),
    ]
