# Generated by Django 5.2.3 on 2026-06-05 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0007_projectnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='chacra_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Solo se permiten números.')], verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fraccion_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Solo se permiten números.')], verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manzana_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Solo se permiten números.')], verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parcela_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Solo se permiten números.')], verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quinta_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Solo se permiten números.')], verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='street_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Solo se permiten números.')], verbose_name='Numero'),
        ),
    ]
