# Generated by Django 5.2.3 on 2026-06-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hone_number',
            new_name='phone_number',
        ),
    ]
