# Generated by Django 5.2.3 on 2026-06-16 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_hone_number_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(default='Estudio de Agrimensura', max_length=120, verbose_name='Nombre del estudio')),
                ('professional_name', models.CharField(blank=True, max_length=120, verbose_name='Profesional')),
                ('license_number', models.CharField(blank=True, max_length=40, verbose_name='Matrícula')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('cbu', models.CharField(blank=True, max_length=40, verbose_name='CBU')),
                ('alias', models.CharField(blank=True, max_length=40, verbose_name='Alias')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Forma de pago')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del estudio',
                'verbose_name_plural': 'Perfiles del estudio',
            },
        ),
    ]
