# Generated by Django 5.2.6 on 2025-12-01 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_admin", "0006_project_project_adm_client__2fdc8c_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del Grupo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo de Trabajo",
                "verbose_name_plural": "Equipos de Trabajo",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProjectShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Compartición"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_shares",
                        to="project_admin.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_shared",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compartido por",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_projects",
                        to="teams.team",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto Compartido",
                "verbose_name_plural": "Proyectos Compartidos",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Miembro"), ("viewer", "Visualizador")],
                        default="viewer",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="teams.team",
                        verbose_name="Equipo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro de Equipo",
                "verbose_name_plural": "Miembros de Equipo",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["owner", "-created"], name="teams_team_owner_i_e191e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["is_active"], name="teams_team_is_acti_6dafc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectshare",
            index=models.Index(
                fields=["team", "is_active"], name="teams_proje_team_id_ae3067_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectshare",
            index=models.Index(
                fields=["project", "is_active"], name="teams_proje_project_58184e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectshare",
            index=models.Index(
                fields=["shared_by", "-shared_at"],
                name="teams_proje_shared__3e1ad3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectshare",
            unique_together={("project", "team")},
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "is_active"], name="teams_teamm_team_id_e0780a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["user", "is_active"], name="teams_teamm_user_id_4436db_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together={("team", "user")},
        ),
    ]
