# Generated by Django 5.2.3 on 2025-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Presupuesto')),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Gastos')),
                ('advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Anticipos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cobranza',
                'verbose_name_plural': 'Cobranzas',
            },
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('movement_type', models.CharField(choices=[('ADV', 'Anticipo'), ('EXP', 'Gasto'), ('EST', 'Presupuesto')], max_length=3, verbose_name='Tipo de Movimiento')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta',
                'verbose_name_plural': 'Movimientos de Cuenta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('total_advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Cobros Total')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Gastos Total')),
                ('income_mensura', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Mensura')),
                ('income_est_parc', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Est Parcelario')),
                ('income_leg', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Legajos')),
                ('income_amoj', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Amojonamiento')),
                ('income_relev', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Relevamiento')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resumenes Mensuales',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
