# Generated by Django 5.2.3 on 2025-07-09 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['account', 'created_at'], name='accounting__account_754cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['movement_type'], name='accounting__movemen_cb8adb_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfinancialsummary',
            index=models.Index(fields=['year', 'month'], name='accounting__year_50c5ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfinancialsummary',
            unique_together={('year', 'month')},
        ),
    ]
