# Generated by Django 5.2.3 on 2025-07-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='expenses',
            new_name='expense',
        ),
    ]
