# Generated by Django 5.2.3 on 2025-07-25 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_expenses_account_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['user', 'movement_type'], name='accounting__user_id_afcb86_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['user', 'created_at'], name='accounting__user_id_34c05c_idx'),
        ),
    ]
